language: cpp

sudo: required
dist: trusty

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4
    - TRAVIS=1
 
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CTEST_TARGET_SYSTEM=Linux-gcc    CTEST_MODEL=Nightly

before_install:
  - sudo add-apt-repository ppa:cs50/ppa -y # for astyle 3.x
  - sudo add-apt-repository ppa:ubuntugis/ppa -y # for gdal 2.x
  - sudo apt-get -qq update
  - sudo apt-get install -y --allow-unauthenticated libgdal-dev astyle 
  - sudo apt-get install -y libhdf5-dev
  - sudo apt-get install mingw-w64

jobs:
  include:
    - stage: Linux build and test
      script:
        - mkdir -p build_lnx
        - cd build_lnx
        - cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Rel -DENABLE_TESTS=ON ..
        - make
        - ctest -VV
    - stage: MinGW Cross-compile Windows build
      script:
        - mkdir -p build_mingw
        - cd build_mingw
        - cmake .. -DCMAKE_TOOLCHAIN_FILE=../Toolchain-mingw32.cmake -DWITH_GDAL=OFF -DENABLE_TESTS=OFF -DWITH_HDF5=OFF ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Rel
        - make
    - stage: Format
      script:
        - cd scripts
        - ./mdal_astyle.sh `find .. -name \*.h* -print -o -name \*.c* -print`

