# Azure Pipelines to build MDAL documentation

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: true
  branches:
    include:
    - master

variables:
  #system.debug: true
  configuration: release
  - group: 'MDAL_VAR_GROUP'

jobs:
  - job: 'Documentation'
    pool:
      vmImage: 'ubuntu-16.04'
    container:
      image: osgeo/proj-docs
      options: --privileged
    steps:
      - script: |
          set -e
          python3 --version
          sphinx-build --version
        displayName: 'Sphinx version'
      - script: |
          set -e
          cd docs
          if find . -name '*.rst' | xargs grep -P '\t'; then echo 'Tabs are bad, please use four spaces in .rst files.'; false; fi
        displayName: 'Lint .rst files'
      - script: |
          set -e
          cd docs
          make html
        displayName: 'Make html'
      - script: |
          set -e
          cd docs
          make latexpdf
        displayName: 'Make pdf'
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: github.com,192.30.253.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYilTQz0B1OXm8ylVFNX1i6cJdveN+g0YDLqeqBzsIIj1PUwWV+vVcQyKXlqyr1pvpIQXoYxImSh8LjnMJzjJ/Csw+tOuxD0wKssEdpPyNRGu+tTYdhI5tNvpMCnkbyA/Sg0vWZgiqUcHxSpwJu/nsX9k4TUYAFlqu/WxJGtu6F8mkgIaEOizmvjjusOtn3/lZCMkZMDascsexEXuVjbwgN8Zb5A5cvfZXm6TJ8oZ8wDxybTDvSCdDtIWuySwCkdlL5/qbzV/zFyTvbPIfSW6Iz/CSlG0Tu6e9jImWCsUI81ttxsxsnf75wUAXdSE2sdd0/hAK/H6rG+B7YCZlhaaj mdal@lutraconsulting.co.uk
          sshPassphrase: $(MDAL_SSH_PASS)
          sshKeySecureFile: 'mdal-docs-ssh-key'
        displayName: 'Install the key'
        condition: notin(variables['Build.Reason'], 'PullRequest')
      - script: |
          set -e
          mv docs/build/html mdal-docs
          rm mdal-docs/mdal.pdf
          cp docs/build/latex/mdal.pdf mdal-docs
          cd mdal-docs
          git init
          git config user.email "mdal@lutraconsulting.co.uk"
          git config user.name "MDAL Bot"
          git remote add origin git@github.com:lutraconsulting/mdal-docs.git
          echo "mdal.xyz" > CNAME
          touch .nojekyll
          git add -A
          git commit -m "Update with https://github.com/lutraconsulting/MDAL/commit/$BUILD_SOURCEVERSION"
          git push -f origin master
        displayName: 'Deploy the docs'
        condition: notin(variables['Build.Reason'], 'PullRequest')
